// Zusammensetzung der Indizes für den Scanner. Die Listen für DAX, MDAX, TecDAX und
// Nasdaq 100 sind von Hand gepflegt (Stand: Herbst 2026) und müssen nach
// Index-Anpassungen aktualisiert werden. Der S&P 500 wird beim nächtlichen Abruf
// automatisch aus einer öffentlichen Liste geladen.

export type Branche =
  | 'Technologie'
  | 'Kommunikation'
  | 'Konsum zyklisch'
  | 'Konsum Basis'
  | 'Gesundheit'
  | 'Finanzen'
  | 'Industrie'
  | 'Grundstoffe'
  | 'Energie'
  | 'Versorger'
  | 'Immobilien';

export interface IndexMitglied {
  symbol: string; // Yahoo-Finance-Symbol
  name: string;
  branche: Branche;
}

export interface IndexDefinition {
  id: string;
  name: string;
  indexSymbol: string; // Yahoo-Finance-Symbol des Index
  mitglieder: IndexMitglied[]; // leer = wird beim Abruf dynamisch geladen
}

type Zeile = [symbol: string, name: string, branche: Branche];

const liste = (zeilen: Zeile[]): IndexMitglied[] => zeilen.map(([symbol, name, branche]) => ({ symbol, name, branche }));

const DAX: Zeile[] = [
  ['ADS.DE', 'Adidas', 'Konsum zyklisch'],
  ['AIR.DE', 'Airbus', 'Industrie'],
  ['ALV.DE', 'Allianz', 'Finanzen'],
  ['BAS.DE', 'BASF', 'Grundstoffe'],
  ['BAYN.DE', 'Bayer', 'Gesundheit'],
  ['BEI.DE', 'Beiersdorf', 'Konsum Basis'],
  ['BMW.DE', 'BMW', 'Konsum zyklisch'],
  ['BNR.DE', 'Brenntag', 'Industrie'],
  ['CBK.DE', 'Commerzbank', 'Finanzen'],
  ['CON.DE', 'Continental', 'Konsum zyklisch'],
  ['DTG.DE', 'Daimler Truck', 'Industrie'],
  ['DBK.DE', 'Deutsche Bank', 'Finanzen'],
  ['DB1.DE', 'Deutsche Börse', 'Finanzen'],
  ['DHL.DE', 'DHL Group', 'Industrie'],
  ['DTE.DE', 'Deutsche Telekom', 'Kommunikation'],
  ['EOAN.DE', 'E.ON', 'Versorger'],
  ['FRE.DE', 'Fresenius', 'Gesundheit'],
  ['FME.DE', 'Fresenius Medical Care', 'Gesundheit'],
  ['G1A.DE', 'GEA Group', 'Industrie'],
  ['HNR1.DE', 'Hannover Rück', 'Finanzen'],
  ['HEI.DE', 'Heidelberg Materials', 'Grundstoffe'],
  ['HEN3.DE', 'Henkel', 'Konsum Basis'],
  ['IFX.DE', 'Infineon', 'Technologie'],
  ['MBG.DE', 'Mercedes-Benz', 'Konsum zyklisch'],
  ['MRK.DE', 'Merck KGaA', 'Gesundheit'],
  ['MTX.DE', 'MTU Aero Engines', 'Industrie'],
  ['MUV2.DE', 'Münchener Rück', 'Finanzen'],
  ['PAH3.DE', 'Porsche SE', 'Konsum zyklisch'],
  ['QIA.DE', 'Qiagen', 'Gesundheit'],
  ['RHM.DE', 'Rheinmetall', 'Industrie'],
  ['RWE.DE', 'RWE', 'Versorger'],
  ['SAP.DE', 'SAP', 'Technologie'],
  ['G24.DE', 'Scout24', 'Kommunikation'],
  ['SIE.DE', 'Siemens', 'Industrie'],
  ['ENR.DE', 'Siemens Energy', 'Industrie'],
  ['SHL.DE', 'Siemens Healthineers', 'Gesundheit'],
  ['SY1.DE', 'Symrise', 'Grundstoffe'],
  ['VOW3.DE', 'Volkswagen', 'Konsum zyklisch'],
  ['VNA.DE', 'Vonovia', 'Immobilien'],
  ['ZAL.DE', 'Zalando', 'Konsum zyklisch'],
];

const MDAX: Zeile[] = [
  ['AIXA.DE', 'Aixtron', 'Technologie'],
  ['NDA.DE', 'Aurubis', 'Grundstoffe'],
  ['BC8.DE', 'Bechtle', 'Technologie'],
  ['GBF.DE', 'Bilfinger', 'Industrie'],
  ['AFX.DE', 'Carl Zeiss Meditec', 'Gesundheit'],
  ['EVD.DE', 'CTS Eventim', 'Kommunikation'],
  ['DHER.DE', 'Delivery Hero', 'Konsum zyklisch'],
  ['LHA.DE', 'Lufthansa', 'Industrie'],
  ['DWS.DE', 'DWS Group', 'Finanzen'],
  ['EVK.DE', 'Evonik', 'Grundstoffe'],
  ['FIE.DE', 'Fielmann', 'Konsum zyklisch'],
  ['FRA.DE', 'Fraport', 'Industrie'],
  ['FNTN.DE', 'freenet', 'Kommunikation'],
  ['FPE3.DE', 'Fuchs', 'Grundstoffe'],
  ['GXI.DE', 'Gerresheimer', 'Gesundheit'],
  ['HLAG.DE', 'Hapag-Lloyd', 'Industrie'],
  ['HAG.DE', 'Hensoldt', 'Industrie'],
  ['HOT.DE', 'Hochtief', 'Industrie'],
  ['BOSS.DE', 'Hugo Boss', 'Konsum zyklisch'],
  ['IOS.DE', 'Ionos', 'Technologie'],
  ['JEN.DE', 'Jenoptik', 'Technologie'],
  ['JUN3.DE', 'Jungheinrich', 'Industrie'],
  ['SDF.DE', 'K+S', 'Grundstoffe'],
  ['KGX.DE', 'Kion', 'Industrie'],
  ['KBX.DE', 'Knorr-Bremse', 'Industrie'],
  ['KRN.DE', 'Krones', 'Industrie'],
  ['LXS.DE', 'Lanxess', 'Grundstoffe'],
  ['LEG.DE', 'LEG Immobilien', 'Immobilien'],
  ['NEM.DE', 'Nemetschek', 'Technologie'],
  ['NDX1.DE', 'Nordex', 'Industrie'],
  ['P911.DE', 'Porsche AG', 'Konsum zyklisch'],
  ['PUM.DE', 'Puma', 'Konsum zyklisch'],
  ['RAA.DE', 'Rational', 'Industrie'],
  ['RDC.DE', 'Redcare Pharmacy', 'Konsum Basis'],
  ['R3NK.DE', 'Renk', 'Industrie'],
  ['SRT3.DE', 'Sartorius', 'Gesundheit'],
  ['1SXP.DE', 'Schott Pharma', 'Gesundheit'],
  ['SIX2.DE', 'Sixt', 'Industrie'],
  ['SAX.DE', 'Ströer', 'Kommunikation'],
  ['TLX.DE', 'Talanx', 'Finanzen'],
  ['TMV.DE', 'TeamViewer', 'Technologie'],
  ['TKA.DE', 'thyssenkrupp', 'Grundstoffe'],
  ['TKMS.DE', 'TKMS', 'Industrie'],
  ['8TRA.DE', 'Traton', 'Industrie'],
  ['UTDI.DE', 'United Internet', 'Kommunikation'],
  ['WCH.DE', 'Wacker Chemie', 'Grundstoffe'],
  ['DWNI.DE', 'Deutsche Wohnen', 'Immobilien'],
  ['TEG.DE', 'TAG Immobilien', 'Immobilien'],
  ['STM.DE', 'Stabilus', 'Industrie'],
  ['OBCK.DE', 'Ottobock', 'Gesundheit'],
];

const TECDAX: Zeile[] = [
  ['SAP.DE', 'SAP', 'Technologie'],
  ['IFX.DE', 'Infineon', 'Technologie'],
  ['DTE.DE', 'Deutsche Telekom', 'Kommunikation'],
  ['SHL.DE', 'Siemens Healthineers', 'Gesundheit'],
  ['QIA.DE', 'Qiagen', 'Gesundheit'],
  ['SRT3.DE', 'Sartorius', 'Gesundheit'],
  ['AFX.DE', 'Carl Zeiss Meditec', 'Gesundheit'],
  ['NEM.DE', 'Nemetschek', 'Technologie'],
  ['BC8.DE', 'Bechtle', 'Technologie'],
  ['AIXA.DE', 'Aixtron', 'Technologie'],
  ['JEN.DE', 'Jenoptik', 'Technologie'],
  ['TMV.DE', 'TeamViewer', 'Technologie'],
  ['UTDI.DE', 'United Internet', 'Kommunikation'],
  ['1U1.DE', '1&1', 'Kommunikation'],
  ['FNTN.DE', 'freenet', 'Kommunikation'],
  ['EVT.DE', 'Evotec', 'Gesundheit'],
  ['WAF.DE', 'Siltronic', 'Technologie'],
  ['NDX1.DE', 'Nordex', 'Industrie'],
  ['S92.DE', 'SMA Solar', 'Technologie'],
  ['KTN.DE', 'Kontron', 'Technologie'],
  ['EUZ.DE', 'Eckert & Ziegler', 'Gesundheit'],
  ['IOS.DE', 'Ionos', 'Technologie'],
  ['AOF.DE', 'Atoss Software', 'Technologie'],
  ['ELG.DE', 'Elmos Semiconductor', 'Technologie'],
  ['SMHN.DE', 'Süss MicroTec', 'Technologie'],
  ['DRW3.DE', 'Drägerwerk', 'Gesundheit'],
  ['NA9.DE', 'Nagarro', 'Technologie'],
  ['PNE3.DE', 'PNE', 'Versorger'],
  ['COK.DE', 'Cancom', 'Technologie'],
  ['GFT.DE', 'GFT Technologies', 'Technologie'],
];

const NASDAQ100: Zeile[] = [
  ['AAPL', 'Apple', 'Technologie'],
  ['MSFT', 'Microsoft', 'Technologie'],
  ['NVDA', 'Nvidia', 'Technologie'],
  ['AMZN', 'Amazon', 'Konsum zyklisch'],
  ['GOOGL', 'Alphabet A', 'Kommunikation'],
  ['GOOG', 'Alphabet C', 'Kommunikation'],
  ['META', 'Meta Platforms', 'Kommunikation'],
  ['AVGO', 'Broadcom', 'Technologie'],
  ['TSLA', 'Tesla', 'Konsum zyklisch'],
  ['COST', 'Costco', 'Konsum Basis'],
  ['NFLX', 'Netflix', 'Kommunikation'],
  ['TMUS', 'T-Mobile US', 'Kommunikation'],
  ['ASML', 'ASML', 'Technologie'],
  ['CSCO', 'Cisco', 'Technologie'],
  ['AMD', 'AMD', 'Technologie'],
  ['PEP', 'PepsiCo', 'Konsum Basis'],
  ['AZN', 'AstraZeneca', 'Gesundheit'],
  ['LIN', 'Linde', 'Grundstoffe'],
  ['ADBE', 'Adobe', 'Technologie'],
  ['INTU', 'Intuit', 'Technologie'],
  ['QCOM', 'Qualcomm', 'Technologie'],
  ['TXN', 'Texas Instruments', 'Technologie'],
  ['ISRG', 'Intuitive Surgical', 'Gesundheit'],
  ['AMGN', 'Amgen', 'Gesundheit'],
  ['BKNG', 'Booking Holdings', 'Konsum zyklisch'],
  ['PLTR', 'Palantir', 'Technologie'],
  ['HON', 'Honeywell', 'Industrie'],
  ['AMAT', 'Applied Materials', 'Technologie'],
  ['CMCSA', 'Comcast', 'Kommunikation'],
  ['ARM', 'Arm Holdings', 'Technologie'],
  ['PANW', 'Palo Alto Networks', 'Technologie'],
  ['ADP', 'ADP', 'Industrie'],
  ['GILD', 'Gilead Sciences', 'Gesundheit'],
  ['VRTX', 'Vertex Pharmaceuticals', 'Gesundheit'],
  ['SBUX', 'Starbucks', 'Konsum zyklisch'],
  ['MU', 'Micron', 'Technologie'],
  ['LRCX', 'Lam Research', 'Technologie'],
  ['ADI', 'Analog Devices', 'Technologie'],
  ['MELI', 'MercadoLibre', 'Konsum zyklisch'],
  ['KLAC', 'KLA', 'Technologie'],
  ['INTC', 'Intel', 'Technologie'],
  ['CRWD', 'CrowdStrike', 'Technologie'],
  ['APP', 'AppLovin', 'Technologie'],
  ['MSTR', 'Strategy', 'Technologie'],
  ['CEG', 'Constellation Energy', 'Versorger'],
  ['CTAS', 'Cintas', 'Industrie'],
  ['MDLZ', 'Mondelez', 'Konsum Basis'],
  ['ABNB', 'Airbnb', 'Konsum zyklisch'],
  ['SNPS', 'Synopsys', 'Technologie'],
  ['CDNS', 'Cadence Design', 'Technologie'],
  ['FTNT', 'Fortinet', 'Technologie'],
  ['ORLY', "O'Reilly Automotive", 'Konsum zyklisch'],
  ['DASH', 'DoorDash', 'Konsum zyklisch'],
  ['MAR', 'Marriott', 'Konsum zyklisch'],
  ['PYPL', 'PayPal', 'Finanzen'],
  ['REGN', 'Regeneron', 'Gesundheit'],
  ['MRVL', 'Marvell', 'Technologie'],
  ['CSX', 'CSX', 'Industrie'],
  ['WDAY', 'Workday', 'Technologie'],
  ['ADSK', 'Autodesk', 'Technologie'],
  ['PDD', 'PDD Holdings', 'Konsum zyklisch'],
  ['AEP', 'American Electric Power', 'Versorger'],
  ['ROP', 'Roper Technologies', 'Technologie'],
  ['CHTR', 'Charter Communications', 'Kommunikation'],
  ['NXPI', 'NXP Semiconductors', 'Technologie'],
  ['PCAR', 'Paccar', 'Industrie'],
  ['FAST', 'Fastenal', 'Industrie'],
  ['AXON', 'Axon Enterprise', 'Industrie'],
  ['MNST', 'Monster Beverage', 'Konsum Basis'],
  ['KDP', 'Keurig Dr Pepper', 'Konsum Basis'],
  ['PAYX', 'Paychex', 'Industrie'],
  ['TTWO', 'Take-Two Interactive', 'Kommunikation'],
  ['ROST', 'Ross Stores', 'Konsum zyklisch'],
  ['CPRT', 'Copart', 'Industrie'],
  ['EXC', 'Exelon', 'Versorger'],
  ['VRSK', 'Verisk', 'Industrie'],
  ['FANG', 'Diamondback Energy', 'Energie'],
  ['CCEP', 'Coca-Cola Europacific', 'Konsum Basis'],
  ['XEL', 'Xcel Energy', 'Versorger'],
  ['EA', 'Electronic Arts', 'Kommunikation'],
  ['IDXX', 'Idexx Laboratories', 'Gesundheit'],
  ['BKR', 'Baker Hughes', 'Energie'],
  ['CTSH', 'Cognizant', 'Technologie'],
  ['ODFL', 'Old Dominion Freight', 'Industrie'],
  ['KHC', 'Kraft Heinz', 'Konsum Basis'],
  ['GEHC', 'GE HealthCare', 'Gesundheit'],
  ['TEAM', 'Atlassian', 'Technologie'],
  ['DDOG', 'Datadog', 'Technologie'],
  ['ZS', 'Zscaler', 'Technologie'],
  ['LULU', 'Lululemon', 'Konsum zyklisch'],
  ['CSGP', 'CoStar Group', 'Immobilien'],
  ['TTD', 'The Trade Desk', 'Kommunikation'],
  ['ON', 'ON Semiconductor', 'Technologie'],
  ['DXCM', 'Dexcom', 'Gesundheit'],
  ['WBD', 'Warner Bros. Discovery', 'Kommunikation'],
  ['CDW', 'CDW', 'Technologie'],
  ['BIIB', 'Biogen', 'Gesundheit'],
  ['GFS', 'GlobalFoundries', 'Technologie'],
  ['SHOP', 'Shopify', 'Technologie'],
  ['TRI', 'Thomson Reuters', 'Industrie'],
];

export const INDIZES: IndexDefinition[] = [
  { id: 'dax', name: 'DAX 40', indexSymbol: '^GDAXI', mitglieder: liste(DAX) },
  { id: 'mdax', name: 'MDAX', indexSymbol: '^MDAXI', mitglieder: liste(MDAX) },
  { id: 'tecdax', name: 'TecDAX', indexSymbol: '^TECDAX', mitglieder: liste(TECDAX) },
  { id: 'nasdaq100', name: 'Nasdaq 100', indexSymbol: '^NDX', mitglieder: liste(NASDAQ100) },
  { id: 'sp500', name: 'S&P 500', indexSymbol: '^GSPC', mitglieder: [] },
];

// GICS-Sektoren (S&P-500-Liste) auf die Branchen der App abbilden.
export const GICS_BRANCHE: Record<string, Branche> = {
  'Information Technology': 'Technologie',
  'Communication Services': 'Kommunikation',
  'Consumer Discretionary': 'Konsum zyklisch',
  'Consumer Staples': 'Konsum Basis',
  'Health Care': 'Gesundheit',
  Financials: 'Finanzen',
  Industrials: 'Industrie',
  Materials: 'Grundstoffe',
  Energy: 'Energie',
  Utilities: 'Versorger',
  'Real Estate': 'Immobilien',
};
